### ISSUE TITLE
Question Regarding the Arduino

### ISSUE THREAD

**Issue by Holdi601** [jmriego/brunnerdx#13]
You have listed the Arduino boards need to have an ATmega32UX but i can't find that. The closest thing to that i found was a ATmega32u4 so the x means then any revision of that chip or is that an actual model? And if so why would it not work for instance on the  version with the ATmega328P that seems to be infinitively more common at least in my region?
Thanks for your great open source project :)

**Comment by jmriego** [comment]
hi @Holdi601 ! yes, the ATmega32u4 should work. The X actually stands for any number.

I wouldn't be so sure about the ATmega238P. It's possible that it works, but I'm using some USB Arduino libraries that are not equally supported in all the chips so maybe it requires some fixes. I don't have an ATmega238P so I'd recommend you to get the ATmega32u4 as that should work with no issues
