### ISSUE TITLE
Possible missing effects

### ISSUE THREAD

**Issue by NickClark** [jmriego/brunnerdx#6]
I used to have the vJoy solution (that Brunner officially offered) working. After upgrading my computer,  I could no longer get it to work. I was thrilled to find this project. All the functions in `ForceTest.exe` even worked. I fired up DCS and everything seemed in fine! Even trim! One thing that didn't: rumble when firing. Default Brunner had this. Did they add it custom? or is this just an unsupported effect?

Thanks so much for making this work. Either way, I'm glad to have trim working again in DCS 👍

**Comment by jmriego** [comment]
hi @NickClark ! Glad you're enjoying this program :)

I don't have DCS but I can work with you trying to figure this out. The way I usually do this is by flashing a different Arduino sketch (I'll write something for that) and then we can read what are the exact parameters DCS is trying to send to the FFB joystick.

Probably a silly question, but are you using the exact same DCS module that used to get rumble when firing? Have you flashed Arduino sketches before?

**Comment by NickClark** [comment]
Ya. Pretty sure it's the same. Definitely flashed Arduinos before. After some further discussion with others, I think the built in DCS support in CLS2Sim added effects. It also allowed HW Trim, which we lose with this approach. I think for DCS it would be better with CLS2Sim. Too bad I can't get the vJoy integration working anymore.

**Comment by jmriego** [comment]
OK! I'll prepare an Arduino sketch that will generate some logs that would be useful for me to debug this.

I don't understand what do you mean about the HW trim issue though. You should definitely be able to have hardware trim using this program. That's one of the main reasons why I created this in the first place and have had reports of people using it with both planes and helos

Can you describe a bit more about that issue with the trimming?

**Comment by NickClark** [comment]
At this point it's probably not worth more of your time. Think DCS just doesn't have good FFB for every plane. Mostly I was just wanting to confirm that it really was that bad. In some DCS modules I did have Trim, so it must have just been that one. And I'm getting the feeling, after some searching around online, that there is no FFB on gun fire. I just thought there would be because there was with CLS2SIM. If you want to continue debugging, just so we can be sure, then I'm game.

**Comment by jmriego** [comment]
hi @NickClark !

If you still want to check this, here's the link to the Arduino sketch: https://github.com/jmriego/Fino/tree/debug

All you need to do is to download that repo and in Arduino IDE open the folder where you downloaded all of that code and flash the Fino.ino sketch.
Then open the Serial Monitor and then open in DCS the module that is missing the FFB on gun fire. You should see in the Serial Monitor window a bunch of messages and hexadecimal numbers that if you can paste here I'll have a look at them.

Cheers!
