### ISSUE TITLE
High amount of backlash on high force setting

### ISSUE THREAD

**Issue by TwitchyShell** [jmriego/brunnerdx#8]
On Brunner with 200mm extension and Virpil MongoosT-50CM2, high amount of backlash experienced with force scale set >30.

Small disturbances causes the stick to begin oscillating on either or both axes growing in amplitude, until it rapidly moves max deflection to max deflection opposite side.

Might be helpful to add a dampener function.

**Comment by jmriego** [comment]
that doesn't sound great. I wonder why are you finding this but I have reports of people using it on a high force setting with an extension in the Discord channel. The strange thing is that there's already a dampener function to avoid this for certain types of effects but you might be getting it in a different one.
Do you mind giving me a bit more info about how to reproduce that? It would be great if you could use this app and tell me which effects cause it:
https://github.com/jmriego/Fino/blob/master/reference/ForceTest.exe

**Comment by TwitchyShell** [comment]
Discord might be more convenient; where can I find you?

**Comment by jmriego** [comment]
sounds good! there's this server for everything related to hotas: https://discord.gg/szqaJE7
just text in the #brunner channel and let's see if we can fix this

**Comment by jmriego** [comment]
hi! I know that after talking on Discord it seemed like this was not going to be needed for now but just by chance I stumbled upon something that might have caused this on XPForce.
You should receive a notification when opening the app about the new release. Let me know if it solves it for you 🤞
